### ISSUE TITLE
当番を交換するUI

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#1]
## 内容
個人間での当番の交代を反映できるようにする。

## 対応
メインの画面にボタンを１つ配置。押下で交換する2つを選ぶことができるようにする。
jsonの内容をカレンダーに反映しているが、git上のjsonを書き換えた時に反映できるどうか未確認。

## ボタン名
例（できればもっとかっこよく）
通常時：交換
選択時：決定

**Comment by sleep0001** [comment]
## 実装方針
ブランチ：changeJSON

新規作成
change.js
changejson.css

**Comment by sleep0001** [comment]
日付セル押下で日付の取得（方法検討中）
当番交代のトグルボタンがオンの時は取得した日付を2つまで保持（取得方法の準備でき次第着手）
確定ボタンでデータベースの書き換え
データベースの作成（未着手）

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
日付の取得、antdのCalendarにonSelectがあるのでそれでできそう（コードは綺麗にしてほしい）
![2024-07-14 19 49の画像 (1)](https://github.com/user-attachments/assets/4bc7099e-c521-4996-bd23-35685e81e873)
![2024-07-14 19 49の画像](https://github.com/user-attachments/assets/b98b4ad6-741c-48e5-b349-633721025359)

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/daf3b30f-aedc-4d3a-9783-edf6a1bd2fe1)

onSelectを使用
２つの日付を保持するロジックを作成
（選択時にconsole出力すると値が格納できていない、次の選択時には格納されてるラグのような問題あり）

**Comment by sleep0001** [comment]
>（選択時にconsole出力すると値が格納できていない、次の選択時には格納されてるラグのような問題あり）
useStateフックの動作によるものだった。
非同期の変数なので、更新前に出力、参照すると古い値が得られるそう。
高速で選択できるUIでなさそうなので一旦問題なしと判断。

**Comment by sleep0001** [comment]
https://github.com/sleep0001/cleaner-schedule/commit/d59c34cf81caa903c3e138e16a41e79b4093f30a
ヌルポ
すみませんでした。

**Comment by sleep0001** [comment]
# 課題
- 予定の無い月（～6月）に交換モードオンの状態で移動すると、エラー
- 選択して赤くなった日と同じ日が別の月でも赤くなっている

**Comment by sleep0001** [comment]
>選択して赤くなった日と同じ日が別の月でも赤くなっている
月を移動した時に、onselectが実行されている。（antdの仕様？）

**Comment by sleep0001** [comment]
> 予定の無い月（～6月）に交換モードオンの状態で移動すると、エラー

nullを処理していたが、undefinedが処理できていなかった。
該当箇所
selectDate.date !== null
これだと、selectDateがundefinedの時、trueを返してしまうので後続の処理で落ちてしまう。

**Comment by sleep0001** [comment]
> 選択して赤くなった日と同じ日が別の月でも赤くなっている

表示している月を保持する仕様にした。
onPanelChangeを作成し、currentMonthに表示月が保持される。

日付セルを生成する際、その日付とcurrentMonthが一致しない場合にonselectの以降の処理をスキップするようにしている。

**Comment by sleep0001** [comment]
副産物として、月の前後に表示されている29,30,31や1,2,3などの日付を選択した際にselectDateに反映されることなく月を移動できるようになった。
らっきー

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
DBからのデータ取得とオンオフボタンの作成を結合したい。
現在のtestenvから新規ブランチを作成して、DATABASEからマージして動作を確認する。
ボタンとデータ取得が同じファイルなので競合が発生。次回競合を対処します。おやすみ。

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/57522a93-8376-4708-9625-99e00f5b061c)
![image](https://github.com/user-attachments/assets/4e05ed75-7710-409b-8216-6c9ba31d07b8)
@RyoUchiyamaGenius さん
交換できました。
現状は、日付選択＞ボタン押下＞リロードで当番変更を確認できている。
ボタン押下、APIリクエスト後に画面を更新するようにする。

**Comment by sleep0001** [comment]
土日は選択されないが、祝日等の値がある日は選択可能になっているため、交換できてしまうのが気になる。
安直に全員分の名前を含むか判定するのが無難か。。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
testenv更新しました。
[INFO]: Module not found: Error: Can't resolve 'axios' in '/codebuild/output/src2719632889/src/cleaner-schedule/src'
ローカルだと表示されるのに、ビルドエラー出てて泣いてます。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
testenv更新しました。（ビルドエラーの為のバージョン更新も含め）
変数の変更も含んでいます。
https://testenv.d243jtp3u2p740.amplifyapp.com/

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
2024-06-04と2024-06-05にテスト用の予定を作っています。
テストの際はそちらをお使いいただければと思います。

**Comment by sleep0001** [comment]
トグルオンの状態で予定の無い日（～2024/6）を選択するとエラーになる。
event等の情報がundefindが原因だと思われる。
対処しておきます。

**Comment by sleep0001** [comment]
交換するUIをテスト環境に反映したので当課題はクローズします。
