### ISSUE TITLE
日付選択UIの微修正

### ISSUE THREAD

**Issue by RyoUchiyamaGenius** [sleep0001/cleaner-schedule#10]
選択済みの赤色日付を再押下した時に、その日付をキャンセルできるようにする

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
キャンセルできるようにするなら、selectedDateFirstとSecondをまとめて配列か何かにしたほうが楽かと
どうですか？？

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
useStateについてまだ完全に理解できてないけど、
const [ aaa, setaaa] = useState();
って書くと、setaaa(値)でaaaに値は入るみたい。

配列にすると、どう書けるんだろ

**Comment by RyoUchiyamaGenius** [comment]
昨日書いたときは（なぜか）selectedDate.add()ができなかったから、newSelectedを作ってsetSelectedDateにそれを渡してた
set~の引数に関数渡すこともできるらしく、それならスマートに書けそうな気がしなくもない
![2024-07-14 19 49の画像](https://github.com/user-attachments/assets/5f5eca16-110e-43f1-a99d-c18d110980df)

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
それってhandleselectメソッドの処理が終わっても保持できるの？

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
昨日はできてたはず、今日はわからない
なんかsetSelectedDateしとけば状態もちゃんと変わってselectedDateで今の状態が参照できる、みたいな感じだった気がする

**Comment by sleep0001** [comment]
選択をキャンセルするロジック
```

- selectDateFirstにのみ値があり、選択した日付と等しい場合
    selectDateFirstの値を削除
- selectDateFirstとselectDateSecondの両方に値がある場合
    - 両方の値が等しく、選択した日付とも等しい場合
        selectDateFirst、selectDateSecondの両方を削除
    - 両方の値が等しくなく、selectDateSecondと選択した日付が等しい場合
        selectDateSecondの値を削除
    - 両方の値が等しくなく、selectDateFirstと選択した日付が等しい場合
        selectDateFirstにselectDateSecondを渡し、selectDateSecondはnull

```

その他必要な分岐あったら書いておいてください。

CC:
@RyoUchiyamaGenius さん

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
これって選択中の日付の変数2つ必要なの？
条件分岐ネストして複雑になりそう

配列(ないしset)の想定だと
- 配列に選択した日付が既に含まれている場合
　- 削除する
- 含まれていなくて、すでに選択した日付が2つ未満
　- 追加する
- それ以外
　- なにもせずreturn

スマホだからかマークダウンがうまくつかえない

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
const [selectDate, setSelectDate] = useState([null, null]);
配列はこれでできそうかな。

firstとsecondが一緒の値になっている時両方消さないといけないと思った。
含まれている時は選択した方だけ消したい。


その分岐だけだと色々足りなくない？

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
できます！！たぶん、、、、
毎回チェックしてるからfirstとsecondが同じになることなくない？万が一をケアするならリストじゃなくてセットにすれば絶対同じ値にならないかと

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
一応、今の実装だとfirstとsecondは同じになるよ、setにするのありだ。
jsonみたいにkeyvalueで保持ってことよな

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
完全に理解した
setは重複なしの配列みたいなやつだからkeyvalueではなさそう

**Comment by sleep0001** [comment]
setってどうやって最初に入った方判別するんだ？

**Comment by RyoUchiyamaGenius** [comment]
- setでもつ
   - リストに変換してから使う必要がある
- 最初からリストでもつ
   - indexで削除しなきゃいけない
- object<key: date, value: event>でもつ
   - 削除もできるし値の持ち方もわかりやすい <= 最有力
``` js
if (obj.hasOwnProperty('2024-07-01')) {
    delete obj['2024-07-01'];
}
```

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
交換モードOFFにした時にselectedDate空にしようかと思うんだけど、しないほうが良さげ？？

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
空にした方がいいかも。
オン→日付選択→オフ→オンで選択されてない方が自然な感じする（体感）

**Comment by RyoUchiyamaGenius** [comment]
休日を選択した時に無視するの忘れてた

**Comment by sleep0001** [comment]
休日の無視は欲しいね

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
eventInfo.events.length === 0 で休日判定しようと思ってたのに
祝日だとeventsが['海の日']とかになってて無理です
DBの祝日どうなってる？

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
今と同じ［'〇〇の日'］です。
オブジェクトの中に"日"を含むかどうかって判別できないかな。。
めんどくさいけど、"日","年末年始",空で処理すると思いました。
いい案あれば教えてください。

**Comment by sleep0001** [comment]
なんだったら、1つ追加して［date, event, isholiday］とかにする？0と1かTF使って

**Comment by RyoUchiyamaGenius** [comment]
isHolidayは割とあり
担当者情報と祝日情報は別カラムにしたほうがそれっぽくて、なんなら担当者は別テーブルにしたいかも
今後グループ編成が変わる可能性が一応0じゃないので

**Comment by sleep0001** [comment]
[
date: "yyyy-MM-dd",
event: ［"担当A", "担当B"］,
isholiday: "false"
］

こんな感じ？

**Comment by RyoUchiyamaGenius** [comment]
calendar
[
    date: 日付,
    groupId: 1,
    isHoliday: "false",
    holiday: null
]

group
[
    groupId: 1,
    members: ["内山", "岡谷"]
]

みたいなイメージ
もしもグループ編成が変わったときにメンテが楽
と思ったけど、1日だけグループ編成が変わるとかになるとだるいかも

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
グループ構成変わった時には結局DBも変えないといけないから、そこのメンテ性は考えなくていいのでは？って思ってます。
グループ1の構成を変えたら過去のグループ1も全部変わるし（過去の当番はどうでもいいとか置いといて）、新規でグループ7〜作ったらカレンダー側もgroupidを変えないといけない。

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
それは正論すぎるな
> [
date: "yyyy-MM-dd",
event: ［"担当A", "担当B"］,
isholiday: "false"
］

これで
ただ人が入ってるとこがeventなのは違和感あるのでgroupとかmembersとかがいいな

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん

> eventが違和感

そうなんよ…antdの日付と予定に合わせたらそうなってた。
DBのキーにしちゃっててevnt消せない（変更できない）
ただ、現状eventが文字列になってて（本来は文字列（配列））ちゃんと動作しないから次のようにします（予定）。

［
date:"yyyy-mm-dd",
event:"",
group:［"担当者A","担当者B"］,
isholiday:false
］

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
キーって主キーになってるの？
eventって一意じゃなくない？dateと複合？

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
主キーはdateのはず、
多分ソートキーかな

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
土日祝を一通り選択してみて赤くならないことを確認しました。
ありがとうございます。

**Comment by sleep0001** [comment]
標題の件、対応完了したので当課題はクローズします。
