### ISSUE TITLE
リリースノートとやらを作ってみたい＆サイトっぽくしよう

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#24]
完全に突発的なおもいつき。
書き方とか何も知らない
作業ブランチ
20240808a

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/7412de6d-1753-4478-9045-5fe9fe1df7c1)
![image](https://github.com/user-attachments/assets/34ff0b71-c0f2-42f8-9ecf-d5b19216b7ba)
@RyoUchiyamaGenius さん
ヘッダーとフッターコンポーネントを追加しました。
セルの背景色を目に優しくしました。
![image](https://github.com/user-attachments/assets/b6244b5d-e976-4d68-bfef-e7dd6ab32c1a)
ヘッダーからリリースノートを選択すると、別画面に遷移するようにしました。
![image](https://github.com/user-attachments/assets/c07b273b-eeec-4591-87f8-49b6f27440a4)
遷移先の画面にリリースノートを作成しました。内容は結構ガバです。

**Comment by RyoUchiyamaGenius** [comment]
よいですね

**Comment by RyoUchiyamaGenius** [comment]
いまをv1.0.1とするなら、今後のためにv1.0とv1.1みたいなブランチをつくっておいた方がそれっぽいです。
次の開発分はv1.1にプッシュしていきます。

バージョンはv○.△.□だとすると、既存の機能のバグ修正で□、細かい機能追加で△、なにかをガラッと変えたら○の数字を進めるイメージです。

**Comment by RyoUchiyamaGenius** [comment]
ちなみにv1.0.1よりもv1.1.0の方が↑のイメージには合ってる気がします。
v1.0.0がただのカレンダーなので

**Comment by sleep0001** [comment]
> バージョンはv○.△.□だとすると、既存の機能のバグ修正で□、細かい機能追加で△、なにかをガラッと変えたら○の数字を進めるイメージです。

あ、なるほどぉ
完全にテキトーだった

**Comment by sleep0001** [comment]
ちなみに次回リリース予定のログ表示はここで作ったページ遷移を使う予定でございます。

**Comment by sleep0001** [comment]
優先作業なければCSS周りいじってます

**Comment by sleep0001** [comment]
リリースノートの作成、ヘッダーフッターの作成、リリースノートへのルート設定がそれぞれ完了しテスト環境に反映したので当課題はクローズします。
