### ISSUE TITLE
リクエスト時に結果をフラッシュメッセージとして表示

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#25]
UIとして簡単に変更できてしまう。
リクエスト時にポップアップ（モーダル）で確認画面を出す。

送信後にフラッシュメッセージで成功かエラーかを出力できるようにする。

**Comment by sleep0001** [comment]
https://qiita.com/tomoronn3/items/2496c29878e9f8ae798e

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/f628b748-6eec-42a3-b3ed-b48780969ed5)
こんな感じに表示しています。
リクエストに成功した場合は3秒間このメッセージを表示した後にページをリロードします。

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/b2fece82-1b3f-40b0-8b8e-9704c83362af)
確認画面を表示されるように変更
ついでに変更対象の日付と名前を表示できるようにしました。
キャンセルしたら、トグルボタンをオフにし選択した日付をリセットします。

OKを押すとリクエストが投げられる。
リクエストに成功した場合、モーダルが閉じられる。
同時にSUCCESSを3秒間表示、その後画面をリロード。
失敗した場合、モーダルが閉じられる。
エラーメッセージを3秒間表示。

**Comment by RyoUchiyamaGenius** [comment]
キャンセルしたとき交換モードオフにしないほうがよくない？
選ぶ日付まちがえた！ってときにだるそうだし、ここまでたどり着くってことは日付2つ選んでるはずなので交換する意思はありそう

**Comment by RyoUchiyamaGenius** [comment]
モーダルは別コンポーネントな気がします

**Comment by sleep0001** [comment]
キャンセルした時はオンのままになるようにします。
モーダルは別コンポーネントな気がします。
ぼくもそう思います！（今）

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
これ今コメント見返してたんだけど、成功時ってリロードするしかないんだっけ？
成功ってメッセージ出るのに3秒間変わらずだとユーザーの困惑に繋がる気がしてきました。
再レンダリングできればそっちの方が良くて、見た目に反映されてから成功メッセージ出したいです

**Comment by sleep0001** [comment]
考えます。少々。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
なるほど。
ボタン押したときにAPIリクエスト叩いて更新後のデータを取得すればいいのか。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
取得APIを叩きなおすのではなく、保持しているuseStateのデータを変更内容で更新する方がクレバーだと思いました。ので、そっち採用します。

**Comment by sleep0001** [comment]
フラッシュメッセージが表示でき、テスト環境に反映したので当課題はクローズします。
