### ISSUE TITLE
交換ログ機能の作成

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#3]
## 内容
カレンダーの当番が既存の配列か交換して入ったものか分かりにくいと考えられる。
ページ左右どちらか（または下）にログを表示して交換した場合に更新するような機能を組み込む。

## 対応
まだなんにもかんがえてない。

**Comment by sleep0001** [comment]
![image](https://github.com/sleep0001/cleaner-schedule/assets/142907988/64f6c1aa-b9c9-42ac-8b2f-ec4f85ba22a5)
こんなのもいいかも

**Comment by sleep0001** [comment]
https://github.com/sleep0001/cleaner-schedule/issues/11#issuecomment-2265350764

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/e6060b0c-5f85-4375-8c98-dd9559d97423)
@RyoUchiyamaGenius さん
ログを保存するテーブルを作成できました！！（びっくり）

Date1とPeople1には交換前のレコード情報を持たせるようにする。
Date1とDate2は日付順にした方が綺麗かと思いますが、文字列なので日付への直し方は知りません。

**Comment by sleep0001** [comment]
ログを取得する際は、timestampでソートして表示する予定

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/ec976e99-61b8-4d3e-9b03-15ce7051a79a)
@RyoUchiyamaGenius さん
ログの作成機能できました。

テスト環境更新しています。
内山先生の確認後に本番環境に反映しよっかなって思ってます。
どうでしょうか。

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
動きは問題ない気がします。
axiosとかAPIとか何も知らないマンですが、putの部分は一回のリクエストでまとめられませんか？
response1~response3が変数名ちょっと気に食わないかなと。
```
const responseChange = put(url, dateDetail);
const responseLog = post(url, logDetail);
```
みたいに書いたほうが綺麗に感じます。
あと（一応）DBにリクエスト投げる回数も節約できる気がします。

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
あと一応ですがcatch節のなかでロールバックしたいです。
やり方なんて知りません。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
> axiosとかAPIとか何も知らないマンですが、putの部分は一回のリクエストでまとめられませんか？

たしかに！！！
> あと一応ですがcatch節のなかでロールバックしたいです。

catch節の中でろーるばっく？？？
アーニャさんでもわかるようにおねがいするます

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
指摘、修正しました。
ご確認お願いします。

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
現状だと
1. 一つ目の日付の更新が成功する（response1）
2. 二つ目の日付の更新が失敗する（response2）
3. errorを検知してエラー文を出力する
4. 処理終わり
みたいな流れになると思います。これだと失敗したはずなのに一つ目の日付だけは更新されているってことになりそう。
なので
```
// ここ！！　DBに変更を加える前の状態を保存しておく
      try {
        const response1 = await axios.put('https://d0ns4u2oaj.execute-api.ap-northeast-1.amazonaws.com/items', myInit[0]);
        const response2 = await axios.put('https://d0ns4u2oaj.execute-api.ap-northeast-1.amazonaws.com/items', myInit[1]);
        const response3 = await axios.post('https://9uhunbcmd3.execute-api.ap-northeast-1.amazonaws.com/items', myInit[2]);
        console.log('Success:', response1, response2, response3);
        // 成功後にページをリロード
        window.location.reload();
      } catch (error) {
// ここで保存しておいた状態に戻す（rollback）
        console.log('Error:', error);
      };
```
こんな感じの流れにしたほうが安全だと思います。
（ロールバックはDBの処理を取り消して前の状態に戻すことです）
ただしロールバックって一塊の処理を取り消す操作だった気がしていて、現状は3つの処理をしているので
私の想像通りにできるかわかりません。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
完全に理解した。
ろーるばっく、基情で見た気がする（ちゃんと覚えてください）

実際にテストしている時に、交換が行われてかつ、ログに記録されないことはありましたので、ロールバックができていないと思いました（いわれてみれば）。

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
> @RyoUchiyamaGenius さん 指摘、修正しました。 ご確認お願いします。

ちなみにこれってAPI側の修正も必要ですか？

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
> API側の修正も必要ですか？


8b2934f このコミットの時点でのAPI側の修正は必要ないです。

ただ、ログのテーブルのAPIにDELETEアクションを用意していないので、ロールバックに対応する際に修正する必要があります。

## ロールバックの処理順
- レコードの交換を処理
- ログレコードの作成を処理

上記いずれかがエラーの場合
- 交換が成功している場合は、交換前のレコードで上書き（PUT）
- ログの作成が成功している場合は、ログのレコードを削除（DELETE）
削除するログの特定は考え中

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
さすがです。
ロールバックはreactかなんかがいい感じにやってくれないですかねぇ。
セーブポイントを作っておいて、その状態までロールバックできたら最高です。
（reactというかDynamoDB側のような気がしてきた）

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
軽く調べた感じだと、REACTはフロントエンドなので無さそう。
DynamoDBにトランザクションAPIとやらがあるみたい。
複数の操作を１つの操作として実行してその全てが成功か失敗にできるらしい。

lambdaの記述と構造が一気に変わるからちょっと大変そう。

現状、交換とログは別のlambda関数とテーブルとAPIで動いている。
トランザクション化するとなると、それぞれのlambda関数とAPIを統合する必要がありそうでござんす。( ;∀;)

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
トランザクション化したいね。めんどいだろうけど
バックエンドでfirebaseとか導入するやり方もあるらしい(?)けど、そこまで大ごとにするのもなぁと。
ただロールバックできないのは嫌なので。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
AWSのドキュメント読んでて確かに、同時に交換ボタン押したときに不都合が出そうだなって思いました。（コナミ）

**Comment by sleep0001** [comment]
https://dev.classmethod.jp/articles/dynamodb-transactions-multiple-tables/
この記事が実装に使えそう。

**Comment by sleep0001** [comment]
# トランザクション処理の追加について
lambda関数作成済
API作成済
APIに対してロール付与するポリシーの作成で躓き。
"TransactWriteItems"が存在しない。。。なぜ。。

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/6a9071dc-f6b9-4b69-9ae0-b7c024d42cad)

これ入れてないかも。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
トランザクションに失敗したら、フラッシュメッセージとかでエラーを画面表示したい。

トランザクション処理中、他のリクエストをブロックする等の機能を入れる予定。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
トランザクション処理をできるようにlambdaとAPIを作成しました。
アプリ側には未反映です。（修正はおそらく軽微）
与えるデータ形式とリクエストURLは以下です。

POST：https://c8u7xj98yh.execute-api.ap-northeast-1.amazonaws.com/items

`{
  "changeRecords": [
    {
      "date": "2024-06-04",
      "events": "false",
      "people": ["PersonA","PeopleB"]
    },
    {
      "date": "2024-06-05",
      "events": "false",
      "people": ["PersonC","PeopleD"]
    }
  ],
  "logRecord": {
    "Date1": "2024-06-04",
    "Date2": "2024-06-05",
    "People1": ["PersonA","PeopleB"],
    "People2": ["PersonC","PeopleD"]
  }
}`

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
js書き換えて動作確認しました。
ついでにテスト環境に反映しておきました。

![image](https://github.com/user-attachments/assets/d259cfc7-a503-4c01-bc76-8544b04e16a3)

**Comment by sleep0001** [comment]
モバイル端末から実行すると、window.location.reload()が聞いてないかもしれない。

**Comment by sleep0001** [comment]
window.location.reload(true)にすると解決できる模様。
> スマホブラウザはキャッシュを積極的に利用していることがある。

**Comment by sleep0001** [comment]
そういえばログに記録しているタイムスタンプのタイムゾーンが東京じゃないのが気になってたので修正しておきました。

**Comment by sleep0001** [comment]
ログ機能を作成できましたので、当課題はクローズします。
ログを表示するページの作成は別途課題を起票して扱います。
