### ISSUE TITLE
リリースノートの添削

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#32]
@RyoUchiyamaGenius さん

![image](https://github.com/user-attachments/assets/b4f79b7a-a6df-4ec2-8190-bed9790b0e0e)
![image](https://github.com/user-attachments/assets/7f555ca0-151b-4866-9b94-9e61a1805ce6)

内容の不足や乖離、誤字脱字のレビューをお願いします。
（内容はテスト環境に反映済ですが。

**Comment by RyoUchiyamaGenius** [comment]
v1.0.0の追加した機能として「当番表新規作成」って書いたら、当番表を作成する機能があるっぽくない？
「みんなで見れる当番表」的な見れるだけですよってわかる方がいいと思う。

**Comment by sleep0001** [comment]
当番表新規作成
から
当番表（閲覧のみ）

とか？

**Comment by RyoUchiyamaGenius** [comment]
良いと思います

**Comment by sleep0001** [comment]
プルリク#30に含めておきます。
他に気になる点はありませんか？

**Comment by RyoUchiyamaGenius** [comment]
v1.1.0の使い方ってとこは交換機能の使い方ってことがわかるように書いた方が今後同じ形式で書けるので良いです。
h1(?)で交換機能
h2で使い方とか注意事項とか

**Comment by sleep0001** [comment]
たしかに！！

**Comment by RyoUchiyamaGenius** [comment]
CHANGEボタンは確か全部大文字だったので揃えた方が良さそうです

**Comment by sleep0001** [comment]
h1
![image](https://github.com/user-attachments/assets/0d5ab4a2-3b21-422a-8581-dd804ea2d34b)
h2
![image](https://github.com/user-attachments/assets/b6d18e86-f142-444c-989e-788a7a50f642)

あんまり見た目変わらないから、構成から変えたほうがいいかな
![image](https://github.com/user-attachments/assets/4843798e-abdd-43ea-92ce-27f81f225907)

**Comment by RyoUchiyamaGenius** [comment]
使い方の上に1行「交換機能」を追加するイメージです

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/cfa463fb-d1d9-4395-b78f-9d8e52dadb16)
こんな感じ？

**Comment by sleep0001** [comment]
あ、違うね

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/b2a48027-e455-4e3c-9634-83d839618436)
こう？

**Comment by sleep0001** [comment]
区切り線をどこにいれようか迷ったけど、交換機能の下に無いのは統一感なくてやだな
h1の下には区切り線、h2の下は区切り線無しにしようか

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/1c66f8d8-502b-4d32-a0a0-f0f1206a3f4f)

**Comment by RyoUchiyamaGenius** [comment]
h2って箇条書きみたいにできないんだっけ？

**Comment by sleep0001** [comment]
箇条書きは<ul><li></li></ul>とかにしないといけない

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/90cf42a2-1b39-4f49-94ba-370714dcec2d)
それを反映するとこんな感じ

**Comment by sleep0001** [comment]
他なければこのままマージ進めますがどうでしょうか。

**Comment by RyoUchiyamaGenius** [comment]
大丈夫です

**Comment by sleep0001** [comment]
添削ありがとうございました。
当課題はクローズします。
