### ISSUE TITLE
ビルドエラー

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#38]

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
こっちで扱いましょ

**Comment by RyoUchiyamaGenius** [comment]
filepathがおかしい気がしているので調査中です
ディレクトリ構成どうしてますか？

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/66e3213d-c137-4b22-8183-01c8d8eed0ac)

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/ac27e0f3-f759-4cd7-b366-535e9dc18831)
![image](https://github.com/user-attachments/assets/86bbbd24-812c-40a3-9aeb-57239f600ba8)

**Comment by sleep0001** [comment]
#26と#10ってなんですか？

**Comment by RyoUchiyamaGenius** [comment]
issueごとにcloneしたやつです

**Comment by sleep0001** [comment]
なるほど。
今まではそれでできてたって認識で合ってる？

**Comment by RyoUchiyamaGenius** [comment]
エラーは出てたけどできてたので無視してました、、、

**Comment by sleep0001** [comment]
一回正しいフォルダ構成にしてみて

**Comment by RyoUchiyamaGenius** [comment]
正しいとは？

**Comment by sleep0001** [comment]
cleaner-schedule
├─build
├─node_modules
├─public
│      index.html
│      logo-0804.png
│      manifest.json
│      robots.txt
│
└─src
│    │  calendar.css
│    │  calendar.js
│    │  CalendarComponent.css
│    │  Footer.css
│    │  Footer.js
│    │  Header.css
│    │  Header.js
│    │  index.css
│    │  index.js
│    │  logo.svg
│    │  reportWebVitals.js
│    │
│    └─releasenote
│            releasenote.css
│            v1_0_0.js
│            v1_1_0.js
└─package.json
└─package-lock.json

**Comment by sleep0001** [comment]
あ

**Comment by sleep0001** [comment]
npm startしてる階層が違うとか？？

**Comment by RyoUchiyamaGenius** [comment]
#26でnpm startしてます

**Comment by sleep0001** [comment]
うーーーん
別フォルダの階層にしてみたけど、実行できた。。。
クローンしなおすと？

**Comment by RyoUchiyamaGenius** [comment]
同じです

**Comment by sleep0001** [comment]
わかりません。

**Comment by sleep0001** [comment]
何かエラー変わりましたか？

**Comment by RyoUchiyamaGenius** [comment]
変わりません

**Comment by RyoUchiyamaGenius** [comment]
ディレクトリ名変えたらできました。
reactってディレクトリ名=アプリ名にしなくちゃいけないの？

**Comment by sleep0001** [comment]
わーーーーーい

**Comment by sleep0001** [comment]
そうなんだ

**Comment by RyoUchiyamaGenius** [comment]
もしかしたらappName指定してるからそうなのかもしれない。うーーーん
```
    const compiler = createCompiler({
      appName,
      config,
      urls,
      useYarn,
      useTypeScript,
      webpack,
    });
```

**Comment by sleep0001** [comment]
忘れないようにしとこ・・・

**Comment by sleep0001** [comment]
解消したのでクローズします。
