### ISSUE TITLE
当番交換対応（手動コミット先）

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#5]
コミットコメント雛形

> yyyy-MM-dd to yyyy-MM-dd

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
通知確認用...

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius 
確認用...

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/1445aae1-1df9-4ff4-a084-37aff86f963b)

修正後動作確認したのでクローズ

**Comment by sleep0001** [comment]
DB実装版をリリースしたらクローズ

**Comment by sleep0001** [comment]
DBに反映して不要になるのでクローズします。
