### ISSUE TITLE
二重にログ追加されるバグ

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#51]
高速タップで二重にログが登録される。
クリック時に登録完了するまで押下不可にしたい。
- スピナーくるくるする
- 猫が頑張ってるアニメーションにする

アニメーション面白そう。

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
どうせならカレンダーとログの読み込み中の時も同じアニメーションにしたいなーって思いました。

**Comment by sleep0001** [comment]
使えそうな情報サイト
- https://weblemon.space/how-to-add-a-loading-animation-in-gif-to-a-wordpress-site/
![image](https://github.com/user-attachments/assets/8d1b15b9-ce66-4dff-b278-386513e6af45)
gifが取得できる。実装サンプルあり。
- ユーザーを飽きさせないためのローディングアニメーション10選
https://uxmilk.jp/77624
![image](https://github.com/user-attachments/assets/4cacb6f2-bff3-42c0-9c03-7106775198c6)
ねこさんあり。
![image](https://github.com/user-attachments/assets/a0ebbe86-8e7a-4502-b711-0dc891320174)
こんなのもおしゃれ。

**Comment by RyoUchiyamaGenius** [comment]
>どうせならカレンダーとログの読み込み中の時も同じアニメーションにしたいなーって思いました。

ローダーコンポーネントとして分けるので、作り方にもよるけど好きなところで同じもの出せます。
場所によって表示する画像変えたいならpropsに渡せばいいし。

猫ちゃんは何種類か用意してランダムで出したりしたい。

**Comment by sleep0001** [comment]
> 猫ちゃんは何種類か用意してランダムで出したりしたい。
いいなそれ。


![image](https://github.com/user-attachments/assets/1f48ec11-2ae3-4f2f-8761-c22d58a613ba)
こんな感じでコンポーネントだけ作ってみた
表示方法はしらべちゅー

**Comment by RyoUchiyamaGenius** [comment]
divとimgにスタイル当てて、divは縦横100%、imgは適当な大きさで画面中央、どっちもz-indexで最前面に出しとけばほぼ完成な気がします

**Comment by RyoUchiyamaGenius** [comment]
```
return (
  {isLoading &&
    〈Loader /〉
  }
  etc..
)
```

こんな感じでCalendarのreturnに入れとけばいけないかな？

あと画像いくつか使うならある程度の統一感あったほうがいいと思ってたけど、面倒だからどうでも良くなった

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/b3c375ab-6c94-4ce9-87a5-c05e42e21e80)

setするならここか。

**Comment by RyoUchiyamaGenius** [comment]
あれ、いまisLoadingってないのか
普通にtryの前とかでtrueにして、message出す前にfalseにしとけばいいと思うよ。
待機時間決める必要ある？

**Comment by RyoUchiyamaGenius** [comment]
あ、なんかset~ってすぐには変わらないとかあるんだっけ？
というか状態で保持しておく必要もないかもだけど

**Comment by sleep0001** [comment]
isloadingはカレンダーの日付と担当者の情報を取得する時に使ってるよ
ある程度表示する時間決めて置かないと猫ちゃん出てくるの一瞬でつまんない

猫ちゃんに表示時間付けたいから、ボタンはリクエスト終わるまでdisableって制約付けたい

**Comment by RyoUchiyamaGenius** [comment]
うーん、ボタンにdisabledつけるのはロード中なのに猫が消えるかもだからってことだよね？
ローディングアニメーションがロード中なのに消えるって変だから、やるなら◯秒以上かつロード終わるまで表示じゃないかなぁ

**Comment by RyoUchiyamaGenius** [comment]
あと最初にサイト開いた時のローディングに待機時間は絶対いらないです。
あの瞬間は急いでる可能性があるので

**Comment by sleep0001** [comment]
上記コミットでgifが表示されるコンポーネントだけ作りました。
表示条件にisLoadingを使用しているので、サイトアクセス時にも表示されるようになっています。
> 最初にサイト開いた時のローディングに待機時間は絶対いらないです。

これにするために、isloadingとは別のuseStateを用意します。
表示されているgifのスタイルについては未着手です。
表示される時間は現状、isloadingに紐づくのでリクエスト中のみの表示です。
今後、リクエスト中かつ3秒間のような仕様に変えます。

**Comment by RyoUchiyamaGenius** [comment]
なんかuseStateつかわなくてもいけそうじゃない？
よくわかんないけど

**Comment by sleep0001** [comment]
> なんかuseStateつかわなくてもいけそうじゃない？

使わずに書いてみました。
しかし、常時表示されるようになったり表示されないようになりました。
原因を調べたところ、普通の変数として宣言した場合Reactの再レンダリングにおいてその値の更新を認識できないようです。

> React は useState や useEffect などのフックを使用して状態を管理することで、状態の変更をトリガーに再レンダリングを行います。

勉強になりました。

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/b880ffc9-0622-4b5f-a45b-852fb6c0e415)

【メモ】
モーダルのz-indexを9998より下に指定してみる

**Comment by sleep0001** [comment]
リリースしたのでクローズします
