### ISSUE TITLE
営業の月曜日に担当されている

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#6]
@RyoUchiyamaGenius

![image](https://github.com/user-attachments/assets/428dff10-2792-4727-8d41-cb81211f6e24)

**Comment by RyoUchiyamaGenius** [comment]
ほんとだ、なんでかな〜〜？？？？

**Comment by sleep0001** [comment]
次の月がないから交換できなかったのでは？って思ってる

**Comment by RyoUchiyamaGenius** [comment]
それですね
同じ週で交換できなかったら失敗になるように作った影響
毎週土曜日に交換する処理入れた（気がする）ので交換処理されてなさそう
![2024-07-14 13 35の画像](https://github.com/user-attachments/assets/8e3ca641-41f2-43e8-941f-6a30fb7e80bb)

**Comment by RyoUchiyamaGenius** [comment]
次の新人にバトンタッチするまで、来年の４月上旬も掃除やりそうだけど、来年の５月も追加していい？？
根本解決ではないですが、、、

**Comment by sleep0001** [comment]
現状、4/11まで作ってる。（手動で

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
4月まで作成して3/31も交換しました。
現状自動で交換できてないのは2024/10/07だけ（同じ週で交換できないので）

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
交換先の担当者がその週にいない場合（前週の金曜日担当→翌週月曜日担当）
交換できなくなっていました。

![image](https://github.com/user-attachments/assets/caa41cbc-ad64-459a-9d9e-dde0d7b38c80)
2024/10/7の場合、交換担当が10/15「冨木田岡谷」です。
ここと交換しても大丈夫でしょうか？
この交換をすると10/15,10/16の連日になってしまいますが。。

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
ここで勝手に連日にして文句いわれたら面倒だなぁと思ってました。
交換機能が完成したら10/7だけ営業の2人に手動交換してもらう想定だったけど、、、
交換のルーティンとか考えだすと結局だるそう
とりあえず交換して連日にしておいて、嫌なら交換してもらうとか？？

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
とりあえず連日にしておきます。
ユーザー通知は無しで。

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/8beefc9a-9e2b-4383-89d7-f31bfdfb32ce)
修正後動作確認したのでクローズ
