### ISSUE TITLE
AWSデータベースで使いたい

### ISSUE THREAD

**Issue by sleep0001** [sleep0001/cleaner-schedule#8]
![image](https://github.com/user-attachments/assets/1967307b-c8b2-4634-97fc-71b383e92b33)

![image](https://github.com/user-attachments/assets/e9ea4a9c-c786-4afc-b185-db6754264b47)

ここまで進行したけど、日付全部一個ずつやりたくなくて登録する方法模索中

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
ご確認お願いします。

**Comment by RyoUchiyamaGenius** [comment]
明日調べてみます（たぶん、、、）

**Comment by sleep0001** [comment]
lambda関数の作成
HTTP APIの作成

APIのテストがしたい
postmanをインストール、使い方がイマイチ分からない



参考
https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/http-api-dynamo-db.html

**Comment by sleep0001** [comment]
現状、何かしら操作があるたびにjsonにアクセスされている。
そんなにリクエスト送りたくないので、更新につき1回保持できるようにしたい

**Comment by sleep0001** [comment]
リクエストで項目の取得に成功　わーい

![image](https://github.com/user-attachments/assets/a85da2ff-1c03-4a54-addb-b147a8adf269)

**Comment by sleep0001** [comment]
DynamoDBからの日付取得

![image](https://github.com/user-attachments/assets/db0d33e1-06b0-41ec-8d8d-053e676be916)

![zoomit](https://github.com/user-attachments/assets/76df2e79-04da-4886-90d8-c842b833ae50)

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/42182f55-b19c-401d-9191-1d43451e7edf)
![image](https://github.com/user-attachments/assets/faf8bd35-fa7a-49de-beab-899fbdae834e)
![image](https://github.com/user-attachments/assets/633c28fa-d162-4ec8-94bb-0b494a5c67b9)

APIを使って項目の登録に成功！
今までできていなかった原因、POSTメソッドを用意してなかった(^^♪

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/b89b18ed-e139-4d0a-adba-ef4000e7b32d)
@RyoUchiyamaGenius さん
レコードに登録してみました。
フォーマットはこんな感じでよいですか？
eventsには、休日ならtrue、営業日ならfalseを入れてます。

**Comment by sleep0001** [comment]
2024/07/01~31を登録しました。
それ以上はAPIの書き込み上限のため制限されました。
時間が経てばリセットされると信じています。

**Comment by RyoUchiyamaGenius** [comment]
@sleep0001 
peopleの要素ってキーなんですか？
eventsは文字列でtrue, falseにするとif文で ===trueみたいな書き方になるし、イコール2個と3個の違いを考えなきゃいけない気がします。文字列で固定なので空にできるなら空が扱いやすいかと
API制限はコード書けば1トランザクションでまとめてinsert？的なことできないかな

**Comment by sleep0001** [comment]
> peopleの要素ってキーなんですか？

キーはdateで、今までのeventsを配列（文字列）にしたもの。

> eventsは文字列でtrue, falseにするとif文で ===trueみたいな書き方になるし、イコール2個と3個の違いを考えなきゃいけない気がします。文字列で固定なので空にできるなら空が扱いやすいかと

events（文字列）は必要ないけど、ソートキーの都合で消せない
→何か用途持たせよう
→一旦文字列の判別値でも入れとこか
（BooleanのTFじゃないからイコール2個かな、使うとなるとコード汚くなるからやめとくか）
→無視できるなら無視してもらえると嬉しい

> API制限はコード書けば1トランザクションでまとめてinsert？的なことできないかな

テストでポチポチしすぎただけかも٩( ᐛ )و

**Comment by RyoUchiyamaGenius** [comment]
{"S", "野際"}
これのSって何ですか？

イコール2個だと型を無視したりで、jsってstringは空じゃなければ全部true返すとかだった気がするので動きがよくわかりません、、、
無理にtrue, falseでつかう必要なさそう

**Comment by sleep0001** [comment]
@RyoUchiyamaGenius さん
Sは多分だけど、stringのsだと思います。
文字列だとSなので配列（文字列）だと｛s:〇〇｝になってるんだと思ってます。

**Comment by sleep0001** [comment]
![image](https://github.com/user-attachments/assets/503967d6-0c14-4222-b53f-7723cd45d266)
見た目は同じだけど、データの取得元がJSONからDynamoDBに変更されていることを確認。（歓喜）
CC：@RyoUchiyamaGenius さん

**Comment by sleep0001** [comment]
DynamoDBを導入、lambda関数を作成、APIの作成、リクエストの実装が完了したので当課題はクローズします。
